### ISSUE TITLE
Phrase query evaluation fails due to 'unknown, ambiguous or inaccessible method phrase'

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#1204]
Original query: `(RUNTIME:[34 TO 52] or TEXT_TOKEN:"gte corp") (SCENE:fire)`

In this case, it seems that `Interpreter.call` is reacting to an argument mismatch when it tries to resolve a `content:phrase` method on the ContentFunctions class.

Remote debugging with Intellij, it appears that the first `phrase` method argument (i.e., local var `argv[0]`), which should be 'TEXT_TOKEN', is actually null at this point, resulting in the stacktrace below

Still investigating
```
[tserver.TabletServer] WARN : Failed to get multiscan result
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failure for query 028ccc46-bed5-4568-a65a-2afab26906d2
 .....
Caused by: org.apache.commons.jexl2.JexlException$Method: datawave.query.function.JexlEvaluation.<init>@48![1,57]:
 '(content:phrase(TEXT_TOKEN, termOffsetMap, 'gte', 'corp') 
&& TEXT_TOKEN == 'gte' 
&& TEXT_TOKEN == 'corp' 
&& (SCENE == 'fire')) 
|| (((_Value_ = true) 
  && ((_Bounded_ = true) 
  && (RUNTIME >= '+bE3.4' && RUNTIME <= '+bE5.2'))) 
  && (SCENE == 'fire'));' unknown, ambiguous or inaccessible method phrase
        at org.apache.commons.jexl2.Interpreter.call(Interpreter.java:1062)
        at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1110)
        at datawave.query.jexl.DatawaveInterpreter.visit(DatawaveInterpreter.java:97)
        at org.apache.commons.jexl2.parser.ASTFunctionNode.jjtAccept(ASTFunctionNode.java:18)
        at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1317)
        at datawave.query.jexl.DatawaveInterpreter.visit(DatawaveInterpreter.java:476)
        at org.apache.commons.jexl2.parser.ASTReference.jjtAccept(ASTReference.java:18)
        at datawave.query.jexl.DatawaveInterpreter.visit(DatawaveInterpreter.java:370)
        at org.apache.commons.jexl2.parser.ASTAndNode.jjtAccept(ASTAndNode.java:18)
        at datawave.query.jexl.DatawaveInterpreter.visit(DatawaveInterpreter.java:370)
        at org.apache.commons.jexl2.parser.ASTAndNode.jjtAccept(ASTAndNode.java:18)
        at datawave.query.jexl.DatawaveInterpreter.visit(DatawaveInterpreter.java:370)
        at org.apache.commons.jexl2.parser.ASTAndNode.jjtAccept(ASTAndNode.java:18)
        at datawave.query.jexl.DatawaveInterpreter.visit(DatawaveInterpreter.java:228)
        at org.apache.commons.jexl2.parser.ASTOrNode.jjtAccept(ASTOrNode.java:18)
        at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:946)
        at org.apache.commons.jexl2.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:38)
        at org.apache.commons.jexl2.Interpreter.interpret(Interpreter.java:232)
        at org.apache.commons.jexl2.ExpressionImpl.execute(ExpressionImpl.java:107)
        at datawave.query.function.JexlEvaluation.apply(JexlEvaluation.java:70)
        at datawave.query.function.JexlEvaluation.apply(JexlEvaluation.java:22)
        at datawave.query.iterator.QueryIterator$1.computeNext(QueryIterator.java:790)
        at datawave.query.iterator.QueryIterator$1.hasNext(QueryIterator.java:800)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at datawave.query.iterator.QueryIterator$1.computeNext(QueryIterator.java:788)
        at datawave.query.iterator.QueryIterator$1.hasNext(QueryIterator.java:800)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at datawave.query.iterator.pipeline.Pipeline.run(Pipeline.java:67)
        at datawave.query.iterator.pipeline.SerialIterator.startPipeline(SerialIterator.java:85)
        at datawave.query.iterator.QueryIterator.seek(QueryIterator.java:467)
        ... 11 more
```

**Comment by keith-ratcliffe** [comment]
**UPDATE**

FWIW, all cases of this bug that I investigated exhibited the same pattern, which is that the `TEXT_TOKEN` phrase being evaluated was part of an `OR` expression, as above, where the document in question had no `TEXT` field present...and therefore had no associated `TEXT_TOKEN` entries in any of the indices, and the document did have a match for whatever term happened to be on the left side of the `OR`

I wasn't able to recreate this issue with any of the other content functions (e.g., `content:within`, etc). So, the main culprit here seems to be the relatively large number of overloaded `phrase` methods, making it impossible for the Interpreter to pick one
