### ISSUE TITLE
DateIndexCleanupVisitor doesn't handle ASTNotNode cleanup, causing query failure in VisitorFunction

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#1241]
For example, this query...
```
FOO:bar not #DATE(SOME_DATE, beginDate, endDate)
```
Translates to Jexl as....
```
(FOO == 'bar' && (!(filter:betweenDates(SOME_DATE, 'beginDate', 'endDate')) || !((SHARDS_AND_DAYS = 'SD1,SD2,...,SDN'))))
```
But, in VisitorFunction.apply, the shard-day-hint cleanup in DateIndexCleanupVisitor leaves an orphaned ASTNotNode...
```
(FOO == 'bar' && (!(filter:betweenDates(SOME_DATE, 'beginDate', 'endDate')) || !))
```
Which eventually leads to query parse failure, killing the query...
```
Error:  {
    "Exceptions": [
        {
            "Cause": "org.apache.commons.jexl2.parser.ParseException: parse error",
            "Code": "500-123",
            "Message": "parse error"
        }
    ],
    "HasResults": false,
    "OperationTimeMS": 0,
    "PageNumber": 0,
    "PartialResults": false
}
```
From Query.log...
```
...
Caused by: datawave.query.exceptions.DatawaveFatalQueryException: datawave.webservice.query.exception.QueryException: Something went wrong running your query.
	at datawave.query.jexl.visitors.JexlStringBuildingVisitor.buildQuery(JexlStringBuildingVisitor.java:103)
	at datawave.query.jexl.visitors.JexlStringBuildingVisitor.buildQuery(JexlStringBuildingVisitor.java:120)
	at datawave.query.tables.async.event.VisitorFunction.apply(VisitorFunction.java:225)
	at datawave.query.tables.async.event.VisitorFunction.apply(VisitorFunction.java:51)
	at datawave.query.tables.async.Scan.call(Scan.java:134)
	at datawave.query.tables.async.Scan.call(Scan.java:34)
        ....

```

**Comment by Montana** [comment]
I recommend using `NegationFSM` in this case via it's a lightweight wrapper around another class which has all of the negation pattern finding logic you would expect with something like `ContextAnnotationClass`.
