### ISSUE TITLE
tserver NoClassDefFoundError: org/apache/commons/collections4/map/LRUMap

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#171]
Looks like new commons-collections4 dependency missing in warehouse/assembly dist.xml, pom, etc

**Comment by keith-ratcliffe** [comment]
Sorry. Reopening, b/c I missed the ingest side of this one earlier...

i.e., ingest-libs.sh also needs updating for this...

18/08/13 18:27:53 INFO mapreduce.Job: Task Id : attempt_1534170071176_0203_m_000000_1, Status : FAILED
Error: java.lang.ClassNotFoundException: org.apache.commons.collections4.IteratorUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at datawave.ingest.json.mr.input.JsonRecordReader.setupIterator(JsonRecordReader.java:166)
        at datawave.ingest.json.mr.input.JsonRecordReader.setupReader(JsonRecordReader.java:154)
        at datawave.ingest.json.mr.input.JsonRecordReader.initialize(JsonRecordReader.java:135)
        at datawave.ingest.json.mr.input.JsonInputFormat$1.initialize(JsonInputFormat.java:31)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:548)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:786)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1840)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

**Comment by keith-ratcliffe** [comment]
FYI, @tomnelson...

mvn dependency:tree says we pick up commons-collections:3.2.2 transitively within assemble-datawave as compile dependency for accumulo-core. So, I'm assuming that's ok.

And fwiw, ingest jobs seem to work fine by changing the following in ingest-libs.sh:

from this...
COMMONS_COLLECTIONS_JAR=$(findJar commons-collections)
....to this:
COMMONS_COLLECTIONS_JAR=$(findJar commons-collections4)
 
However, haven't proven conclusively that old commons-collections isn't still needed on the classpath for some of the other ingest scripts that we have, so may be safer for us just augment ingest-libs.sh with a new var, i.e., 

COMMONS_COLLECTIONS4_JAR=$(findJar commons-collections4)
....
CLASSPATH=${CLASSPATH}:${COMMONS_COLLECTIONS4_JAR}
