### ISSUE TITLE
Build/test DW on Hadoop 3.x

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#176]
This ticket tracks progress on DW updates required for Hadoop 3.x. Currently, the hadoop3x branch successfully builds/tests/deploys DW on (Apache) **Hadoop 3.1.1** and **Accumulo 1.9.2**

More details below...

**Comment by keith-ratcliffe** [comment]
Currently, ingest examples in the quickstart seem to be working fine, but web service deploy/test is failing due to errors such as the following:

```
# From $WILDFLY_HOME/standalone/server.log
....
MSC000001: Failed to start service jboss.deployment.subunit."datawave-ws-deploy-application-2.3.0-SNAPSHOT-dev.ear"."datawave-ws-modification-2.3.0-SNAPSHOT.jar".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.subunit."datawave-ws-deploy-application-2.3.0-SNAPSHOT-dev.ear"."datawave-ws-modification-2.3.0-SNAPSHOT.jar".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of subdeployment "datawave-ws-modification-2.3.0-SNAPSHOT.jar" of deployment "datawave-ws-deploy-application-2.3.0-SNAPSHOT-dev.ear"
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
        at org.apache.hadoop.io.WritableComparator.<init>(WritableComparator.java:128)
        at org.apache.hadoop.io.WritableComparator.<init>(WritableComparator.java:116)
        at org.apache.hadoop.io.Text$Comparator.<init>(Text.java:360)
        at org.apache.hadoop.io.Text.<clinit>(Text.java:374)
        at datawave.webservice.modification.cache.ModificationCacheBean.<clinit>(ModificationCacheBean.java:66)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.jboss.invocation.proxy.AbstractProxyFactory.afterClassLoad(AbstractProxyFactory.java:95)
        at org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:166)
        at org.jboss.invocation.proxy.AbstractProxyFactory.getCachedMethods(AbstractProxyFactory.java:150)
        at org.jboss.as.ejb3.component.singleton.SingletonComponentDescription$6.configure(SingletonComponentDescription.java:211)
        at org.jboss.as.ee.component.DefaultComponentViewConfigurator.configure(DefaultComponentViewConfigurator.java:67)
        at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:92)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper from [Module "org.apache.hadoop.common:main" from local module loader @1c2c22f3 (finder: local module finder @18e8568 (roots: /home/skratcl/datawave-new/contrib/datawave-quickstart/wildfly/modules,/home/skratcl/datawave-new/contrib/datawave-quickstart/wildfly/modules/system/layers/base))]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
        ... 19 more
....
```

**Comment by keith-ratcliffe** [comment]
Discovered Hadoop 3.x transitive **dependency conflict**, i.e., between our declared **commons-beanutils-core:1.7.0** and Hadoop's transitive dep **commons-beanutils:1.9.3** (by way of its dependency on commons-configuration2)

**Resolution**: Upgraded all our declared beanutils dependencies to commons-beanutils:1.9.3

This was rather painful to diagnose/fix, because the only symptom was that some unknown unit test within ingest-core was hanging indefinitely and never failing. Finally, had to track down a MiniAccumuloCluster log directory under /tmp to see the ClassNotFoundException that was killing it's TSERVER instance.
