### ISSUE TITLE
Issue w/commit for #152

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#243]
The 3955dbc72727c2c9dee106d165b5eaef2183ee21 commit seems to have affected the configured table name propagation, such that PushdownScheduler is not getting the overidden table name value(s) from the build properties anymore. Not sure why yet, still investigating

E.g., In this case, the actual table name was 'datawave.shard', namespace-prefixed. 
 
.....
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table shard does not exist
        at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:109)
        at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:92)
        at datawave.query.scheduler.PushdownScheduler.concatIterators(PushdownScheduler.java:149)
        at datawave.query.scheduler.PushdownScheduler.iterator(PushdownScheduler.java:120)
        ... 163 more

**Comment by keith-ratcliffe** [comment]
@ivakegg @apmoriarty looks like the problem is that **ShardQueryConfiguration** instances no longer get the   incoming (spring-configured) **ShardQueryLogic.tableName** property copied into the**ShardQueryConfiguration.shardTableName** property

That copy used to be performed by **ShardQueryConfigurationFactory.createShardQueryConfigurationFromConfiguredLogic(...)**

So, we're just missing the logic to synchronize those two props now that ShardQueryConfigurationFactory has been removed
