### ISSUE TITLE
During ingest, MarkingFunctions context fails to load causing jobs to fail, and other issues

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#306]
First, there are a couple of minor issues:

* findJars.sh and ingest-libs.sh need to be updated in order to add new accumulo-utils.jar and common-utils.jar to ingest classpath
* datawave assembly dist.xml needs to be updated to include common-utils.jar in the archive

**The main issue**

After correcting the issues above, we still get the following errors below during ingest job execution.
The bottom line is that the spring context init fails with **java.lang.ClassNotFoundException: datawave.marking.ColumnVisibilitySecurityMarking**

`ColumnVisibilitySecurityMarking` lives in `services/base-rest-responses`, but I'm not sure we really want to add that jar to the ingest classpath, for this class alone. A reasonable home for the class could be accumulo-utils instead? Although, maybe adding base-rest-responses to the ingest classpath isn't a huge deal. @brianloss thoughts?
```
19 19:20:33,438 WARN [main] org.springframework.context.support.ClassPathXmlApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [datawave.marking.ColumnVisibilitySecurityMarking] for bean with name 'marking' defined in URL [jar:file:/home/me/dev/datawave/contrib/datawave-quickstart/data/hadoop/yarn/local/filecache/75/datawave-ingest-configuration-2.5.0-SNAPSHOT.jar!/MarkingFunctionsContext.xml]; nested exception is java.lang.ClassNotFoundException: datawave.marking.ColumnVisibilitySecurityMarking
2019-01-19 19:20:33,438 WARN [main] datawave.marking.MarkingFunctions$Factory: Could not load spring context files. got org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [datawave.marking.ColumnVisibilitySecurityMarking] for bean with name 'marking' defined in URL [jar:file:/home/me/dev/datawave/contrib/datawave-quickstart/data/hadoop/yarn/local/filecache/75/datawave-ingest-configuration-2.5.0-SNAPSHOT.jar!/MarkingFunctionsContext.xml]; nested exception is java.lang.ClassNotFoundException: datawave.marking.ColumnVisibilitySecurityMarking
2019-01-19 19:20:33,455 WARN [main] org.springframework.context.support.ClassPathXmlApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: 

############## Here's the main culprit ###############

org.springframework.beans.factory.CannotLoadBeanClassException: 
Cannot find class [datawave.marking.ColumnVisibilitySecurityMarking] 
for bean with name 'marking' defined in URL [jar:file:/home/me/dev/datawave/contrib/datawave-quickstart/data/hadoop/yarn/local/filecache/75/datawave-ingest-configuration-2.5.0-SNAPSHOT.jar!/MarkingFunctionsContext.xml]; nested exception is
java.lang.ClassNotFoundException: datawave.marking.ColumnVisibilitySecurityMarking

######################################################

2019-01-19 19:20:33,455 WARN [main] datawave.marking.MarkingFunctions$Factory: Could not load spring context files. got org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [datawave.marking.ColumnVisibilitySecurityMarking] for bean with name 'marking' defined in URL [jar:file:/home/me/dev/datawave/contrib/datawave-quickstart/data/hadoop/yarn/local/filecache/75/datawave-ingest-configuration-2.5.0-SNAPSHOT.jar!/MarkingFunctionsContext.xml]; nested exception is java.lang.ClassNotFoundException: datawave.marking.ColumnVisibilitySecurityMarking
2019-01-19 19:20:33,457 WARN [main] datawave.ingest.data.config.ingest.BaseIngestHelper: No index fields or blacklist fields specified, not generating index fields for error
2019-01-19 19:20:33,457 WARN [main] datawave.ingest.data.config.ingest.BaseIngestHelper: No reverse index fields or blacklist reverse index fields specified, not generating reverse index fields for error
2019-01-19 19:20:33,457 INFO [main] datawave.ingest.mapreduce.handler.shard.AbstractColumnBasedHandler: ErrorShardedDataTypeHandler configured.
2019-01-19 19:20:33,553 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.IllegalArgumentException: Failed to parse security marking configuration
	at datawave.ingest.mapreduce.handler.error.ErrorShardedDataTypeHandler.setup(ErrorShardedDataTypeHandler.java:161)
	at datawave.ingest.mapreduce.EventMapper.loadDataType(EventMapper.java:342)
	at datawave.ingest.mapreduce.EventMapper.map(EventMapper.java:511)
	at datawave.ingest.mapreduce.EventMapper.map(EventMapper.java:93)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1912)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.NullPointerException
	at datawave.ingest.mapreduce.handler.error.ErrorShardedDataTypeHandler.setup(ErrorShardedDataTypeHandler.java:159)
	... 11 more
```

**Comment by brianloss** [comment]
I could go either way, although I’m leaning towards just adding the base responses to the classpath. I have to double check, but I think some of the iterators (maybe they’re in our companion project) use base rest responses too. I think in the end it’s not “bad” to include that jar-the only thing that makes them rest responses are the JAX-RS annotations but there’s nothing else in that module that ties anything to a web service. Well, that end extending the web application exception.
