### ISSUE TITLE
Ingesting data failed starting with ERROR job.BulkIngestMapFileLoader

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#411]
I am trying to ingest some data but keep getting the following error - in log file and in console (I removed duplicates).  What could be causing this error?  Any help would be appreciated.

ERRORS ON SCREEN
===============
19/04/12 13:23:26 INFO mapreduce.Job: Task Id : attempt_1555073048090_0001_m_000000_0, Status : FAILED
Error: java.util.NoSuchElementException: Type myjson does not exist in the registry
	at datawave.ingest.data.TypeRegistry.get(TypeRegistry.java:89)
	at datawave.ingest.data.TypeRegistry.getType(TypeRegistry.java:107)
	at datawave.ingest.data.config.DataTypeHelperImpl.initType(DataTypeHelperImpl.java:68)
	at datawave.ingest.data.config.DataTypeHelperImpl.setup(DataTypeHelperImpl.java:37)
	at datawave.ingest.data.config.CSVHelper.setup(CSVHelper.java:157)
	at datawave.ingest.json.config.helper.JsonDataTypeHelper.setup(JsonDataTypeHelper.java:32)
	at datawave.ingest.json.mr.input.JsonRecordReader.createHelper(JsonRecordReader.java:269)
	at datawave.ingest.input.reader.AbstractEventRecordReader.initializeEvent(AbstractEventRecordReader.java:97)
	at datawave.ingest.input.reader.AbstractEventRecordReader.initialize(AbstractEventRecordReader.java:75)
	at datawave.ingest.json.mr.input.JsonRecordReader.initialize(JsonRecordReader.java:118)
	at datawave.ingest.json.mr.input.JsonInputFormat$1.initialize(JsonInputFormat.java:31)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:554)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:792)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:177)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:171)

.......

19/04/12 13:23:40 INFO mapreduce.Job:  map 100% reduce 0%
19/04/12 13:23:41 INFO mapreduce.Job: Job job_1555073048090_0001 failed with state FAILED due to: Task failed task_1555073048090_0001_m_000000
Job failed as tasks failed. failedMaps:1 failedReduces:0

19/04/12 13:23:42 INFO mapreduce.Job: Counters: 9
	Job Counters 
		Failed map tasks=4
		Launched map tasks=4
		Other local map tasks=3
		Data-local map tasks=1
		Total time spent by all maps in occupied slots (ms)=86248
		Total time spent by all reduces in occupied slots (ms)=0
		Total time spent by all map tasks (ms)=10781
		Total vcore-milliseconds taken by all map tasks=10781
		Total megabyte-milliseconds taken by all map tasks=11039744
......

19/04/12 13:23:42 INFO client.RMProxy: Connecting to ResourceManager at localhost/127.0.0.1:8032
19/04/12 13:23:42 INFO mapred.ClientServiceDelegate: Application state is completed. FinalApplicationStatus=FAILED. Redirecting to job history server
19/04/12 13:23:43 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:10020. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
......
Exception in thread "main" java.io.IOException: java.net.ConnectException: Your endpoint configuration is wrong; For more details see:  http://wiki.apache.org/hadoop/UnsetHostnameOrPort
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:344)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:429)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:804)
	at org.apache.hadoop.mapreduce.Cluster.getJob(Cluster.java:214)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:602)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:600)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
	at org.apache.hadoop.mapred.JobClient.getJobUsingCluster(JobClient.java:600)
	at org.apache.hadoop.mapred.JobClient.getJobInner(JobClient.java:610)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:640)
	at datawave.ingest.mapreduce.job.IngestJob.run(IngestJob.java:428)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at datawave.ingest.mapreduce.job.IngestJob.main(IngestJob.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:244)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
......
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:690)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:794)
	at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568)
	at org.apache.hadoop.ipc.Client.call(Client.java:1399)
	... 29 more

===============
ERRORS IN LOG FILE
===============
ERROR job.BulkIngestMapFileLoader: Unable to retrieve major compaction stats: java.net.SocketException: Connection reset

After several of same errors

19/04/12 12:08:41 ERROR job.BulkIngestMapFileLoader: Unable to retrieve major compaction stats: null
19/04/12 12:08:41 INFO job.BulkIngestMapFileLoader: There are 0 compactions currently running or queued.
19/04/12 12:08:41 INFO job.BulkIngestMapFileLoader: Time since map files last brought online: 1555070921s
19/04/12 12:08:46 INFO client.ClientConfiguration: Loaded client configuration file /cloud/accumulo/conf/client.conf
19/04/12 12:08:46 ERROR job.BulkIngestMapFileLoader: Unable to retrieve major compaction stats: null
19/04/12 12:08:50 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x10000756c5c000d, likely server has closed socket, closing socket connection and attempting reconnect
19/04/12 12:08:51 INFO client.ClientConfiguration: Loaded client configuration file /cloud/accumulo/conf/client.conf
19/04/12 12:08:52 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
19/04/12 12:08:52 INFO zookeeper.ClientCnxn: Socket error occurred: localhost/127.0.0.1:2181: Connection refused
19/04/12 12:08:52 WARN zookeeper.ZooCache: Saw (possibly) transient exception communicating with ZooKeeper, will retry
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /accumulo/instances/accumulo

......

19/04/12 12:09:11 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
19/04/12 12:09:11 INFO zookeeper.ClientCnxn: Socket error occurred: localhost/127.0.0.1:2181: Connection refused
19/04/12 12:09:11 WARN zookeeper.ZooCache: Saw (possibly) transient exception communicating with ZooKeeper, will retry
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /accumulo/instances/accumulo
        
.........

19/04/12 12:13:01 INFO zookeeper.ClientCnxn: Socket error occurred: localhost/127.0.0.1:2181: Connection refused
/cloud/dw-ingest/bin/ingest/map-file-bulk-loader.sh: line 63: 24255 Killed                  $MAP_FILE_LOADER_COMMAND_PREFIX $INGEST_HADOOP_HOME/bin/hadoop --config $WAREHOUSE_HADOOP_CONF jar ${DATAWAVE_INGEST_CORE_JAR} datawave.ingest.mapreduce.job.BulkIngestMapFileLoader $WORKDIR $PATTERN $WAREHOUSE_INSTANCE_NAME $WAREHOUSE_ZOOKEEPERS $USERNAME $PASSWORD -majcThreshold ${MAP_LOADER_MAJC_THRESHOLD} -sleepTime 5000 -numHdfsThreads 100 -numThreads 20 -majcCheckInterval 1 -maxDirectories 200 -numAssignThreads 60 -seqFileHdfs $INGEST_HDFS_NAME_NODE -srcHdfs $WAREHOUSE_HDFS_NAME_NODE -destHdfs $WAREHOUSE_HDFS_NAME_NODE -jt $WAREHOUSE_JOBTRACKER_NODE $MAP_FILE_LOADER_EXTRA_ARGS $EXTRA_ARGS ${INGEST_CONFIG[@]}
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource all-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource dateindex-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource edge-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource error-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource metadata-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource mycsv-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource myjson-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource nyctlc-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource shard-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Adding resource wikipedia-ingest-config.xml
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Set sleep time to 5000ms
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Will wait to bring map files online if there are more than 32000 running or queued major compactions.
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Will not bring map files online unless at least 0ms have passed since last time.
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Will check the majcThreshold and majcDelay every 1 bulk loads.
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Processing a max of 200 directories
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using 20 bulk load threads
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using 100 HDFS operation threads
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using 60 bulk assign threads
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using hdfs://localhost:8020 as the file system containing the original sequence files
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using hdfs://localhost:8020 as the source file system
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using hdfs://localhost:8020 as the destination file system
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using localhost:8032 as the jobtracker
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using 24101 as the shutdown port
19/04/12 13:17:37 INFO job.BulkIngestMapFileLoader: Using FIFO processing order
19/04/12 13:17:38 INFO job.BulkIngestMapFileLoader: Found table priorities: {datawave.metadata=30, datawave.error_i=30, datawave.shardIndex=30, datawave.loadDates=30, datawave.error_r=30, datawave.shard=30, datawave.error_s=30, datawave.edge=30, datawave.dateIndex=30, datawave.shardReverseIndex=30, datawave.error_m=30}
19/04/12 13:17:38 INFO job.BulkIngestMapFileLoader: Listening for shutdown commands on port 24101
19/04/12 13:17:38 INFO job.BulkIngestMapFileLoader: Starting process to monitor map files.
19/04/12 13:17:43 INFO client.ClientConfiguration: Loaded client configuration file /cloud/accumulo/conf/client.conf
19/04/12 13:17:43 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03, built on 06/29/2018 04:05 GMT
19/04/12 13:17:43 INFO zookeeper.ZooKeeper: Client environment:host.name=node1
19/04/12 13:17:43 INFO zookeeper.ZooKeeper: Client environment:java.version=1.8.0_191
19/04/12 13:17:43 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
19/04/12 13:17:43 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/java/jdk1.8.0_191-amd64/jre
@

**Comment by rqualis-altamiracorp** [comment]
I am not sure if this is related/causing the error, but the related log files for these config files are reporting that the following files are missing:

/cloud/dw-ingest/config/bulkFlagMaker.xml
/cloud/dw-ingest/config/WikipediaFlagMakerConfig.xml
/cloud/dw-ingest/config/liveFlagMaker.xml

I cannot find them in your repo 

datawave/properties/dev.propereties
      FLAG_MAKER_CONFIG=/local/datawave-ingest/config/liveFlagMaker.xml,/local/datawave-ingest/config/bulkFlagMaker.xml,/local/datawave-ingest/config/WikipediaFlagMakerConfig.xml

**Comment by keith-ratcliffe** [comment]
Hi,
```
 INFO zookeeper.ClientCnxn: Socket error occurred: localhost/127.0.0.1:2181: Connection refused INFO zookeeper.ClientCnxn: Socket error occurred: localhost/127.0.0.1:2181: Connection refused
```
...is usually a sign that ZooKeeper isn't running, which is bad since it's required for both DW and Accumulo to function properly. Looks like the same is probably true for your M/R job history server, although that service is less critical

I'm assuming, based on your log output, that your intention was to run a single-node instance of DW/Accumulo/Hadoop/ZK. And I'm assuming that you opted not to use the contrib/datawave-quickstart setup, and to manually configure/install DW and other services instead

Is that correct? Just need to make sure those assumptions are correct before I can offer more advice

P.S., The current properties/dev.properties file is more or less a fictional example at the moment, and it probably should be documented as such and cleaned up a bit. Sorry for the confusion.

**Comment by keith-ratcliffe** [comment]
@rqualis-altamiracorp , any further assistance required, or can this be closed?

**Comment by rqualis-altamiracorp** [comment]
Resolved. please close
