### ISSUE TITLE
Recent change to AggregatingReducer breaks ingest

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#425]
While testing locally, I found that [this change](https://github.com/NationalSecurityAgency/datawave/blob/186b2deb1e8cb401c9e80ee288845078d7476630/warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java#L381) breaks ingest, (see stacktrace below). The exception is due to the `isValidEncoding(columns)` logic within `ColumnSet.decodeColumns(column)` b/c what we pass in is a literal '*' in this case and thatis deemed to be invalid by `isValidEncoding`

Still investigating the ideal fix. Will also investigate adding unit test coverage for this case
```
19/04/30 16:25:52 INFO mapreduce.Job: Task Id : attempt_1556641296382_0003_m_000000_2, Status : FAILED
Error: java.io.IOException: Failed to initialized class datawave.ingest.mapreduce.job.writer.DedupeContextWriter from property ingest.event.mapper.context.writer.class
        at datawave.ingest.mapreduce.EventMapper.setup(EventMapper.java:245)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:142)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1912)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.IllegalArgumentException: Invalid encoding *
        at org.apache.accumulo.core.iterators.conf.ColumnSet.decodeColumns(ColumnSet.java:126)
        at datawave.ingest.mapreduce.job.reduce.AggregatingReducer$CustomColumnToClassMapping.<init>(AggregatingReducer.java:381)
        at datawave.ingest.mapreduce.job.reduce.AggregatingReducer.configureAggregators(AggregatingReducer.java:256)
        at datawave.ingest.mapreduce.job.reduce.AggregatingReducer.configureReductionInterface(AggregatingReducer.java:125)
        at datawave.ingest.mapreduce.job.reduce.AggregatingReducer.setup(AggregatingReducer.java:107)
        at datawave.ingest.mapreduce.job.reduce.BulkIngestKeyDedupeCombiner.setup(BulkIngestKeyDedupeCombiner.java:38)
        at datawave.ingest.mapreduce.job.writer.DedupeContextWriter.setup(DedupeContextWriter.java:35)
        at datawave.ingest.mapreduce.EventMapper.setup(EventMapper.java:243)
        ... 8 more
```

**Comment by keith-ratcliffe** [comment]
Turns out that the old PerColumnIteratorConfig.decode method used previously was just more forgiving, in that it would return a new Text instance initialized with "*" as expected by DW, regardless of the fact that it wasn't properly encoded to begin with.

So, my workaround was just to avoid the decode step altogether whenever column == "*"
