### ISSUE TITLE
Get DataWave Quickstart to create the queryMetrics_s table properly.

### ISSUE THREAD

**Issue by jzgithub1** [NationalSecurityAgency/datawave#499]
Probably related to ticket #190.

I am seeing this error when I start up DataWave Quickstart (via this command:allStop --hard; allUninstall && allInstall) :
16 15:33:08,099 [start.Main] ERROR: Thread 'datawave.ingest.util.GenerateShardSplits' died.
org.apache.accumulo.core.client.TableNotFoundException: Table datawave.queryMetrics_s does not exist
	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.addSplits(TableOperationsImpl.java:432)
	at datawave.ingest.util.GenerateShardSplits.main(GenerateShardSplits.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.accumulo.start.Main$2.run(Main.java:170)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jzgithub1** [comment]
I saw the table create.  Maybe we will re-open.
