### ISSUE TITLE
Accumulo 2.0 Migration

### ISSUE THREAD

**Issue by milleruntime** [NationalSecurityAgency/datawave#533]
Accumulo 2.0 is now released: https://accumulo.apache.org/release/accumulo-2.0.0/
Opening this issue to put notes and as a reference for work to be done to get Datawave working with 2.0. 

Currently the code doesn't compile for 2.0 so that is probably a good place to start.

**Comment by milleruntime** [comment]
I have got Datawave master branch to compile with Accumulo 2.0 on a branch [here](https://github.com/milleruntime/datawave/tree/accumulo-2.0).  Changes I found that were not specific to 2.0 I have made into pull requests.  I will try to keep this branch up to date with latest master until it can be brought into the Datawave repo.   The next biggest requirement will be upgrading Guava to something that works, see #514

**Comment by milleruntime** [comment]
I saw this Exception in some reflection code when installing ingest:
```
Exception in thread "main" java.lang.RuntimeException: Unable to call generateInitialTableProperties
	at datawave.ingest.table.config.AbstractTableConfigHelper.generateInitialTableProperties(AbstractTableConfigHelper.java:122)
	at datawave.ingest.table.config.AbstractTableConfigHelper.areAggregatorsConfigured(AbstractTableConfigHelper.java:146)
	at datawave.ingest.table.config.AbstractTableConfigHelper.setAggregatorConfigurationIfNecessary(AbstractTableConfigHelper.java:86)
	at datawave.ingest.table.config.ShardTableConfigHelper.configureShardTable(ShardTableConfigHelper.java:167)
	at datawave.ingest.table.config.ShardTableConfigHelper.configure(ShardTableConfigHelper.java:140)
	at datawave.ingest.mapreduce.job.IngestJob.configureTablesIfNecessary(IngestJob.java:1225)
	at datawave.ingest.mapreduce.job.IngestJob.createAndConfigureTablesIfNecessary(IngestJob.java:1162)
	at datawave.ingest.mapreduce.job.IngestJob.configureTables(IngestJob.java:743)
	at datawave.ingest.mapreduce.job.IngestJob.run(IngestJob.java:298)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at datawave.ingest.mapreduce.job.IngestJob.main(IngestJob.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
Caused by: java.lang.NoSuchMethodException: org.apache.accumulo.core.iterators.IteratorUtil.generateInitialTableProperties(boolean)
	at java.lang.Class.getMethod(Class.java:1786)
	at datawave.ingest.table.config.AbstractTableConfigHelper.generateInitialTableProperties(AbstractTableConfigHelper.java:119)
```

**Comment by ceellis** [comment]
Noted the following exception when running the datawave quickstart tests:

 ERROR [datawave.query.tables.ScannerSession] (default task-1) [cn=test a. user, ou=example developers, o=example corp, c=us] [a23bb2a5-f929-4424-a92f-2bf028d63c51] Exception discovered on hasNext call: java.lang.ClassCastException: datawave.webservice.common.connection.WrappedAccumuloClient cannot be cast to org.apache.accumulo.core.clientImpl.ClientContext
        at datawave.query.scheduler.PushdownFunction.binRanges(PushdownFunction.java:180)
        at datawave.query.scheduler.PushdownFunction.redistributeQueries(PushdownFunction.java:145)
        at datawave.query.scheduler.PushdownFunction.apply(PushdownFunction.java:84)
        at datawave.query.scheduler.PushdownFunction.apply(PushdownFunction.java:45)
        at com.google.common.collect.Iterators$5.transform(Iterators.java:757)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at datawave.query.tables.BatchScannerSession.run(BatchScannerSession.java:284)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:748)

**Comment by SethSmucker** [comment]
We're on Accumulo 2.1.4, closing.
