### ISSUE TITLE
On Hadoop 3, ShardedTableMapFile may throw "IllegalArgumentException: Wrong FS: ..." and kill bulk ingest jobs

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#591]
In Hadoop 3 environments where ingest and query clusters are distinct, I've observed that [ShardedTableMapFile.getReader](https://github.com/NationalSecurityAgency/datawave/blob/227fbfc5b90b57a87cf1ba538c106a23fb962199/warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardedTableMapFile.java#L71) can throw...
```
java.lang.IllegalArgumentException: Wrong FS: hdfs://query-cluster/path/to/tableName_shards.lst, expected: hdfs://ingest-cluster
    at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:781)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:240)
    at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1569)
    ...
```
...depending on how the M/R job is configured
 
That is, our usage of `FileSystem.get(conf)` here to get the FS always yields **hdfs://ingest-cluster** (as per `fs.defaultFS` from site config), and that conflicts with the actual file path, if configured for the job as follows....
```
...
<property>
    <name>datawave.ingest.mapreduce.job.ShardedTableMapFile.tableName</name>
    <value>hdfs://query-cluster/path/to/tableName_shards.lst</value>
</property>
...
```
A better approach is to use `FileSystem.get(new URI(shardMapFileName), conf)` instead. (I'm not really sure why we weren't doing it that way all along, but the current code clearly works in the scenario described, at least on previous versions of Hadoop)

But since the `SequenceFile.Reader` constructor we're using here has been deprecated for quite a while, this is probably better....
```
  return new SequenceFile.Reader(conf, Reader.file(new Path(shardMapFileName)));
```
Internally, this constructor gets the FS based on the given Path, as appropriate

**Comment by keith-ratcliffe** [comment]
Fixed by 018bd40e
