### ISSUE TITLE
FlagMaker dies abruptly with cryptic error message, and related issues

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#629]
**Summary of Issues**
------------------------------
1. Cryptic ERROR message (see below) gives no clue why the FlagMaker died. Is the `System.exit` even appropriate in this case?
2. Confusingly, `SimpleFlagDistributor.next` uses different semantics for `maxFlags` (sometimes it equates to file count, sometimes to `InputFile.getMaps()`) depending how many files are in the input dir, and there seems to be no way choose which semantics you want for your data type. (E.g., what if my files aren't splittable and I only want file count semantics? Is there a way to force that behavior)

**Details**
------------------------------
When the size in bytes of input files is large relative to the FlagMaker's `maxFlags` value, the `SimpleFlagDistributor.next` method may send an empty `Collection<InputFile>` to `FlagMaker.writeFlagFile`, which causes FlagMaker to die immediately after startup with the following....
```
ERROR [datawave.util.flag.FlagMaker] An unexpected exception occurred. Exiting
java.lang.IllegalArgumentException: inFiles for Flag file
	at datawave.util.flag.FlagMaker.writeFlagFile(FlagMaker.java:402)
	at datawave.util.flag.FlagMaker.processFlags(FlagMaker.java:250)
	at datawave.util.flag.FlagMaker.run(FlagMaker.java:221)
	at datawave.util.flag.FlagMaker.main(FlagMaker.java:126)
INFO [datawave.util.flag.FlagMaker] FlagMaker Exiting.
```
This can be replicated easily with the quickstart (_maxFlags == 4_) by attempting to ingest 4 or more large-ish wikipedia XML files with individual file sizes exceeding 4x128MB, with all files being present in the HDFS input directory prior to FlagMaker startup

**maxFlags (file count semantics)**

Interestingly, if you feed the files to the HDFS input dir at most 3 (_maxFlags - 1_) at a time, then `SimpleFlagDistributor.next` will blindly [add all of them](https://github.com/NationalSecurityAgency/datawave/blob/4aff179c82c73b71d2a877f64654e7ef6ae2d107/warehouse/ingest-core/src/main/java/datawave/util/flag/processor/SimpleFlagDistributor.java#L48) to the `Collection<InputFile>`, and they'll get sent thru normally

**maxFlags (InputFile.getMaps() semantics)**

But if there are _maxFlags_ or more of these files present during the current execution, then a [completely different](https://github.com/NationalSecurityAgency/datawave/blob/4aff179c82c73b71d2a877f64654e7ef6ae2d107/warehouse/ingest-core/src/main/java/datawave/util/flag/processor/SimpleFlagDistributor.java#L60) decision-making algorithm is used....
```
class InputFile {
...
    public int getMaps() {
        double maps = (blocksize == 0 ? 1 : (double) filesize / blocksize);
        return (int) Math.ceil(maps);
    }
}
```
...and if `InputFile.getMaps()` for each file happens to be greater than `maxFlags`, then the `IllegalArgumentException` above is thrown and the FlagMaker dies

**Comment by keith-ratcliffe** [comment]
**Workarounds**
------------------

- Move files into the HDFS input directory at most (_maxFlags - 1_) at a time, and wait until the flag file is written before moving more
- Set _maxFlags_ value to be greater than (largest file size in bytes / blocksize), and restart the FlagMaker
