### ISSUE TITLE
periodic test failures

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#637]
This is to track test failures that we see periodically so that we collaborate on fixing them:

**Comment by ivakegg** [comment]
```
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.426 s <<< FAILURE! - in datawave.query.FilterFieldsQueryTest
[ERROR] testEqCityAndEqContinentBlackListWithHitList(datawave.query.FilterFieldsQueryTest)  Time elapsed: 0.093 s  <<< FAILURE!
java.lang.AssertionError: missing return field(CITY)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:380)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:325)
        at datawave.query.FilterFieldsQueryTest.testEqCityAndEqContinentBlackListWithHitList(FilterFieldsQueryTest.java:271)

[ERROR] testEqCityAndEqContinentBlackList(datawave.query.FilterFieldsQueryTest)  Time elapsed: 0.074 s  <<< FAILURE!
java.lang.AssertionError: missing return field(CODE)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:380)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:325)
        at datawave.query.FilterFieldsQueryTest.testEqCityAndEqContinentBlackList(FilterFieldsQueryTest.java:236)

[ERROR] testBlackListMultiValueIncluded(datawave.query.FilterFieldsQueryTest)  Time elapsed: 0.066 s  <<< FAILURE!
java.lang.AssertionError: missing return field(COUNTRY)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:380)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:330)
        at datawave.query.FilterFieldsQueryTest.testBlackListMultiValueIncluded(FilterFieldsQueryTest.java:207)
```

**Comment by ivakegg** [comment]
```
[ERROR]   MaxExpansionRegexQueryTest.testMaxValueAnyFieldFilterExclude:157->AbstractFunctionalQuery.runTest:287->AbstractFunctionalQuery.runTest:303->AbstractFunctionalQuery.runTestQuery:349->AbstractFunctionalQuery.runTestQuery:388 results do not match expected expected:<3> but was:<0>

[ERROR]   MaxExpansionRegexQueryTest.testMaxIvaratorResultsFailsQuery:271->AbstractFunctionalQuery.runTest:294->AbstractFunctionalQuery.runTest:310->AbstractFunctionalQuery.runTestQuery:356->AbstractFunctionalQuery.runTestQuery:395 results do not match expected expected:<5> but was:<0>
```

**Comment by ivakegg** [comment]
```
[ERROR] testLimitedCollisionsForPastFewMonths(datawave.ingest.mapreduce.partition.BalancedShardPartitionerTest)  Time elapsed: 0.162 s  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: -248
        at datawave.ingest.mapreduce.partition.BalancedShardPartitionerTest.setUp(BalancedShardPartitionerTest.java:52)
```

**Comment by jwomeara** [comment]
I've seen this one as well:
```
[ERROR] testEqCityAndEqContinentBlackList(datawave.query.FilterFieldsQueryTest)  Time elapsed: 9.444 s  <<< FAILURE!
java.lang.AssertionError: missing return field(CITY)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:380)
        at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:325)
        at datawave.query.FilterFieldsQueryTest.testEqCityAndEqContinentBlackList(FilterFieldsQueryTest.java:228)
```

**Comment by keith-ratcliffe** [comment]
Maybe worth noting that I've observed failed builds periodically, from what seems to be race condition related to read/write of POMs during a multi-threaded Maven builds. Wondering if it might be worth disabling MT builds for a bit just to see if some of these other issues clear up(?)

Here's a small snippet from one of these, from a failed CI pipeline:
(The `*.pom.part (No such file or directory)` is always the symptom, and repeats numerous times for several modules)
```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.springframework:spring-aop:pom:5.0.8.RELEASE from/to central (https://repo.maven.apache.org/maven2): 
/builds/datawave/datawave/.m2/repository/org/springframework/spring-aop/5.0.8.RELEASE/spring-aop-5.0.8.RELEASE.pom.part (No such file or directory)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:422)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:224)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:201)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom (DefaultArtifactDescriptorReader.java:261)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor (DefaultArtifactDescriptorReader.java:192)
   ....
   ....
(MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by ivakegg** [comment]
I believe the MaxExpansionRegexQueryTest periodic failures have been resolved.  The FilterFieldsQueryTest however has not been resolved.

**Comment by keith-ratcliffe** [comment]
Just observed this one, which then passed on a subsequent try...
```
[ERROR]   QueryExecutorBeanTest.testPredict:467 
  Unexpected method call QueryPredictor.predict(Type: RunningQuery User: null UserDN: CN=Guy Some Other soguy, OU=MY_SUBDIVISION, OU=MY_DIVISION, O=ORG, C=US Date: Wed Dec 04 19:49:05 GMT 2019 QueryId: f910ccb4-b3f1-4a30-a9d2-6f02dfc6b117 Query: FOO == BAR Query Plan: null Query Type: RunningQuery Query Logic: EventQueryLogic Query Name: null Authorizations: PRIVATE,PUBLIC ColumnVisibility: null Begin Date: Wed Dec 04 19:49:05 GMT 2019 End Date: Wed Dec 04 19:49:05 GMT 2019 Parameters: [] Host: null SetupTime(ms): 0 CreateCallTime(ms): -1 PageTimes(ms): [] ProxyServers: null Lifecycle: NONE ErrorCode: null ErrorMessage: null Source Count: 0 NextCount: 0 Seek Count: 0 Yield Count: 0 Doc Ranges: 0 FI Ranges: 0 Login Time: -1 Predictions: []
): expected: 1, actual: 0
```

**Comment by brianloss** [comment]
On the accumulo-2.0 branch, this one is flaky:
```
[ERROR] Failures: 
[ERROR]   MaxExpansionRegexQueryTest.testMaxIvaratorResultsFailsQuery:276->AbstractFunctionalQuery.runTest:315->AbstractFunctionalQuery.runTest:331->AbstractFunctionalQuery.runTestQuery:377->AbstractFunctionalQuery.runTestQuery:416 results do not match expected expected:<5> but was:<0>
```

**Comment by brianloss** [comment]
> 
> 
> On the accumulo-2.0 branch, this one is flaky:
> 
> ```
> [ERROR] Failures: 
> [ERROR]   MaxExpansionRegexQueryTest.testMaxIvaratorResultsFailsQuery:276->AbstractFunctionalQuery.runTest:315->AbstractFunctionalQuery.runTest:331->AbstractFunctionalQuery.runTestQuery:377->AbstractFunctionalQuery.runTestQuery:416 results do not match expected expected:<5> but was:<0>
> ```

Actually, we're seeing flakiness for this one on the master branch too.

**Comment by ivakegg** [comment]
This time the BalancedShardPartitionerTest was witnessed to periodically fail (master branch)

**Comment by ivakegg** [comment]
MaxExpansionRegexQueryTest still periodically fails in master

**Comment by ivakegg** [comment]
Tanisha is working this one

**Comment by ivakegg** [comment]
MaxExpansionRegexQueryTest still periodically fails in release/version3.0

**Comment by ivakegg** [comment]
I can no longer get FilterFieldsTest to fail.  This pull request may have fixed it: #638.

**Comment by ivakegg** [comment]
I was able to get QueryExecutorBeanTest to fail using "while [[ 1 ]]; do mvn test -pl :datawave-ws-query -Dtest=QueryExecutorBeanTest -DskipITs; if [[ $? != 0 ]]; then break; fi; done":
```
[ERROR] Failures: 
[ERROR] datawave.webservice.query.runner.QueryExecutorBeanTest.testCloseActuallyCloses(datawave.webservice.query.runner.QueryExecutorBeanTest)
[ERROR]   Run 1: QueryExecutorBeanTest.testCloseActuallyCloses:733 createQuery thread died before reaching initialize: java.lang.AssertionError: 
  Unexpected method call Persister.remove(datawave.webservice.query.QueryImpl@62e6714b[queryLogicName=EventQueryLogic,queryName=<null>,expirationDate=Fri Nov 20 14:37:02 GMT 2020,uuid=e9d3172a-b6c2-4272-b25e-0b75940b0a05,pagesize=10,pageTimeout=0,maxResultsOverride=NA,query=FOO == BAR,queryAuthorizations=PRIVATE,PUBLIC,userDN=CN=Guy Some Other soguy, OU=MY_SUBDIVISION, OU=MY_DIVISION, O=ORG, C=US,owner=<null>,parameters=[],dnList=<null>,columnVisibility=<null>,beginDate=Thu Nov 19 14:37:02 GMT 2020,endDate=Thu Nov 19 14:37:02 GMT 2020]):
    Persister.create("cn=guy some other soguy, ou=my_subdivision, ou=my_division, o=org, c=us", [cn=guy some other soguy, ou=my_subdivision, ou=my_division, o=org, c=us], PRIVATE|PUBLIC, "EventQueryLogic", datawave.webservice.query.QueryParametersImpl@c35375ed, {audit.userDn=[cn=guy some other soguy, ou=my_subdivision, ou=my_division, o=org, c=us], audit.columnVisibility=[PRIVATE|PUBLIC], audit.logicClass=[EventQueryLogic]}): expected: 1, actual: 1
    Persister.findById(<any>): expected: at least 0, actual: 0
```

**Comment by ivakegg** [comment]
I got a new one to fail using "while [[ 1 ]]; do mvn test -pl :datawave-query-core -Dtest=\!MaxExpansionRegexQueryTest -DskipITs; if [[ $? != 0 ]]; then break; fi; done":
```
[ERROR] Failures: 
[ERROR]   AnyFieldQueryTest.testOrOr:302->AbstractFunctionalQuery.runTest:312->AbstractFunctionalQuery.runTest:328->AbstractFunctionalQuery.runTestQuery:374->AbstractFunctionalQuery.runTestQuery:413 results do not match expected expected:<5> but was:<3>
```

**Comment by ivakegg** [comment]
I have not successfully seen a failure with the BalancedShardPartitionerTest, but I will let it run all day to see if anything happens.

**Comment by ivakegg** [comment]
This one took a long time to show up but:
```
Failures: 
[ERROR]   MultiValueQueryTest.testVirtual:104->AbstractFunctionalQuery.runTest:312->AbstractFunctionalQuery.runTest:328->AbstractFunctionalQuery.runTestQuery:374->AbstractFunctionalQuery.runTestQuery:413 results do not match expected expected:<5> but was:<2>
```

**Comment by plainolneesh** [comment]
[ERROR] Failures: 
[ERROR]   IndexOnlyQueryTest.testOr:125->AbstractFunctionalQuery.runTest:312->AbstractFunctionalQuery.runTest:328->AbstractFunctionalQuery.runTestQuery:374->AbstractFunctionalQuery.runTestQuery:413 results do not match expected expected:<5> but was:<3>

Marking this one for me to circle back to.

**Comment by ivakegg** [comment]
Saw this in release/version3.0 today:
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.554 s <<< FAILURE! - in datawave.webservice.common.cache.SharedCacheCoordinatorTest
[ERROR] testSharedCounterUpdateAfterConnectionLost(datawave.webservice.common.cache.SharedCacheCoordinatorTest)  Time elapsed: 13.552 s  <<< FAILURE!
java.lang.AssertionError: Counter never updated after restart. expected:<42> but was:<10>
	at datawave.webservice.common.cache.SharedCacheCoordinatorTest.testSharedCounterUpdateAfterConnectionLost(SharedCacheCoordinatorTest.java:205)

**Comment by ivakegg** [comment]
Just saw this one again:
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.962 s <<< FAILURE! - in datawave.query.FilterFieldsQueryTest
[ERROR] testRegexBlacklist(datawave.query.FilterFieldsQueryTest)  Time elapsed: 2.811 s  <<< FAILURE!
java.lang.AssertionError: missing return field(CITY)
	at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:380)
	at datawave.query.FilterFieldsQueryTest.runTest(FilterFieldsQueryTest.java:325)
	at datawave.query.FilterFieldsQueryTest.testRegexBlacklist(FilterFieldsQueryTest.java:247)

**Comment by lbschanno** [comment]
I have also seen periodic test failures in SharedCacheCoordinatorTest #1069.

**Comment by plainolneesh** [comment]
> [ERROR] Failures:
> [ERROR] IndexOnlyQueryTest.testOr:125->AbstractFunctionalQuery.runTest:312->AbstractFunctionalQuery.runTest:328->AbstractFunctionalQuery.runTestQuery:374->AbstractFunctionalQuery.runTestQuery:413 results do not match expected expected:<5> but was:<3>
> 
> Marking this one for me to circle back to.


UPDATE: I do not see this as an issue anymore.
