### ISSUE TITLE
Sporadic query failures in VisitorFunction on /{QueryID}/next call

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#744]
Thus far, attempts to replicate this behavior intentionally have failed, but the issue has been observed several times on release/version2.8 while running multiple distinct queries in Wildfly, with the failing query usually being of the form "(A OR B) AND (C OR D)" or something similar.

**Query client**: /next call produces
 ```
{
    "Exceptions": [
        {
            "Message": "java.lang.IllegalArgumentException: value is null",
            "Code": "500-14",
            "Cause": "java.lang.RuntimeException: java.lang.IllegalArgumentException: value is null"
        }
    ],
    "HasResults": false,
    "OperationTimeMS": 0,
    "PageNumber": 0,
    "PartialResults": false
} 
```
**Wildfly Query.log**:
```
ERROR [datawave.query.tables.CondensedRangeStreamScanner] (RangeBundlerIterator for 95838b13-5cfa-44df-9e23-053b77e7f5b2) 
Exception discovered on hasNext call: java.lang.IllegalArgumentException: value is null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
        at org.apache.accumulo.core.client.IteratorSetting.addOption(IteratorSetting.java:240)
        at datawave.query.tables.async.event.VisitorFunction.apply(VisitorFunction.java:242)
        at datawave.query.tables.async.event.VisitorFunction.apply(VisitorFunction.java:52)
        at datawave.query.tables.async.Scan.call(Scan.java:133)
        at datawave.query.tables.async.Scan.call(Scan.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
So far, subsequent retries of the failed query have always succeeded.

We've speculated that the **newQuery** variable could be null at [line 242](https://github.com/NationalSecurityAgency/datawave/blob/release/version2.8/warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java#L242) as a result of a race condition involving the **previouslyExpanded** map, as the VisitorFunction instance is shared.

Related to #736, #705

**Comment by keith-ratcliffe** [comment]
Update: 94050e4 seems to have resolved an additional issue that we observed during testing: inconsistent query plans for identical queries (usually wildcard queries yielding lots of results), which was causing inconsistent search results over the same data
