### ISSUE TITLE
Allow JSON in POST Body for REST calls

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/datawave#834]
It appears that the only way to pass query parameters to the rest endpoint is by using `application/x-www-form-urlencoded` data. It would be nice to be able to just pass JSON in a POST body without having to worry about URL encoding. Looking at the implementation, it appears to just follow the "bag of properties" model that Datawave uses in the server side of things and just allowing URL encoding was just easy.

Another advantage is that some systems will cap URLs at 2048 bytes, but allow longer POST bodies.

Finally, if using something with history enabled (like a web browser) the full URLs can be stored in the history, which would risk exposing sensitive query information.

**Comment by drewfarris** [comment]
Good to hear from you @klucar. I ran into the JSON issue as well just this week. 

Spring Boot's rest template was using `application/json` by default and, I encountered this issue during a `create` call. The exception on this server-side is:
```
java.lang.IllegalArgumentException: Cannot find a deserializer for non-concrete Map type [map type; class javax.ws.rs.core.MultivaluedMap, [simple type, class java.lang.String] -> [collection type; class java.util.List, contains [simple type, class java.lang.String]]]
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createMapDeserializer(BasicDeserializerFactory.java:1368)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:384)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
``` 

Naturally, it was straightforward to tell spring to use an `application/w-www-form-urlencoded` for encoding for the POST data, but this might not be as easy in all cases.

> Finally, if using something with history enabled (like a web browser) the full URLs can be stored in the history, which would risk exposing sensitive query information.

Could you describe this a little further? What request are you making via GET that would include sensitive query information?

**Comment by klucar** [comment]
I'm doing some side work that's using datawave. I've built a query UI in R/Shiny and have an R package that wraps the REST interface in R. 

Your point about POST from a browser is correct. I was using POSTMAN to test the API and forgot it was doing POST for that. Although I should try a GET and see if it just works. 

I have another ticket coming that may supersede this one though.

**Comment by drewfarris** [comment]
I'd love to check out the R/Shiny UI at some point if you're able to share.
